services:
  traefik:
    container_name: traefik
    image: cgr.dev/chainguard/traefik:latest
    labels:
      traefik.enable: true
      traefik.http.routers.api.entrypoints: websecure
      traefik.http.routers.api.rule: Host(`traefik.bodkys.house`)
      traefik.http.routers.api.middlewares: authentik@file
      traefik.http.routers.api.tls: true
      traefik.http.routers.api.service: api@internal
    ports:
      - 443:443
    command: >
      --api.dashboard
      --providers.docker
      --providers.docker.exposedByDefault=false
      --providers.file.directory=/etc/traefik
      --entrypoints.websecure.address=:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    external: true
