services:
  traefik:
    container_name: traefik
    image: traefik:v2.11.2
    labels:
      traefik.http.routers.api.entrypoints: websecure
      traefik.http.routers.api.rule: Host(`traefik.bodkys.house`)
      traefik.http.routers.api.tls: true
      traefik.http.routers.api.service: api@internal
      traefik.http.routers.api.middlewares: bauth
      traefik.http.middlewares.bauth.basicauth.users: dbodky:$$2y$$10$$w1Ab1308owoOgu7h/a2EEODHkchrn2QtykALaM9Wvcd/Qgpnrc6du
    ports:
      - 443:443
    command: >
      --api.dashboard
      --providers.docker
      --providers.docker.exposedByDefault=false
      --providers.file.directory=/etc/traefik
      --entrypoints.websecure.address=:443
      --entrypoints.websecure.forwardedHeaders.trustedIPs=172.0.0.1/32,192.168.1.0/24
      --entrypoints.websecure.proxyProtocol.trustedIPs=172.0.0.1/32,192.168.1.0/24
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/traefik
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik: {}
