services:
  authentik-postgresql:
    container_name: authentik-postgresql
    image: postgres:12-alpine
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - /var/lib/authentik/database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    restart: unless-stopped

  authentik-redis:
    container_name: authentik-redis
    image: redis:alpine
    command: --save 60 1 --loglevel warning
    volumes:
      - /var/lib/authentik/redis:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    restart: unless-stopped

  authentik:
    container_name: authentik
    image: ghcr.io/goauthentik/server:2024.4.1
    labels:
      traefik.http.routers.authentik.entrypoints: websecure
      traefik.http.routers.authentik.rule: Host(`id.bodkys.house`)
      traefik.http.routers.authentik.tls: true
      traefik.http.routers.authentik.service: authentik
    command: server
    env_file:
      - .env
    environment:
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    depends_on:
      - authentik-postgresql
      - authentik-redis
    restart: unless-stopped

  authentik-worker:
    container_name: authentik-worker
    image: ghcr.io/goauthentik/server:2024.4.1
    command: worker
    environment:
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    env_file:
      - .env
    depends_on:
      - authentik-postgresql
      - authentik-redis
    restart: unless-stopped
